# Generated by Django 5.0.6 on 2026-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('airline_code', models.CharField(blank=True, max_length=5)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('stops', models.PositiveSmallIntegerField(default=0)),
                ('booking_url', models.URLField(blank=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Both')], default='EMAIL', max_length=10)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_error', models.TextField(blank=True)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('raw_offer', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-alert_sent_at'],
            },
        ),
    ]
