# Generated by Django 5.0.6 on 2026-05-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='routes.trackedroute'),
        ),
    ]
